### PR TITLE
[MOBFND-134] Upgrade to version 4.0.5

### PR DESCRIPTION
**Pull request by kevinfarst-earnin**
## Jira Link

https://earnin.atlassian.net/browse/MOBFND-134

## Implementation Details

- Upgrade SDK to 4.0.5
- Change `NS_SWIFT_NAME` in `SEGReachability.h` from `Reachability` to `SEGReachability` to avoid module name collision with `ReachabilitySwift`

## Checklist

3rd party SDK PRs:
- [x] **No code modifications were made as part of this PR**, unless absolutely necessary (3rd party library usage changes, keys change etc.)
- [ ] 3rd party library tracker spreadsheet has been updated [[LINK](https://docs.google.com/spreadsheets/d/1QrpcoNxet0HlYHeNWP74GomztMCQiGa5zhTa_bluUKQ/edit#gid=0)]
- [ ] Listed this PR in the appropriate section of the Release Tracker for the version it is taking effect. [[LINK](https://docs.google.com/spreadsheets/d/1X3TDt40cgbzfTv5iIEVuyCxOTqpMJg6nwUHM8ECxhN8/edit)]
- [x] Communicated the change widely in [#mobiledev-all](https://earnin.slack.com/archives/CD9LTF7FE)

### CODE REVIEW

**Review by nabi-earnin — APPROVED** [review]

**Review by kamaldeep-earnin — APPROVED** [review]

**Comment by kamaldeep-earnin** [comment]
Conflicts

**Review by nabi-earnin — CHANGES_REQUESTED** [review]
Is this supposed to go to `master`?

**Comment by kevinfarst-earnin** [comment]
@kamaldeep-earnin @nabi-earnin yes, I'm only opening the PR to show the changes, I'll have to merge the updates manually into the master branch

**Comment by kevinfarst-earnin** [comment]
@kamaldeep-earnin @nabi-earnin conflicts resolved 👍

**Review by nabi-earnin — APPROVED** [review]

**Pull request merged**
